name: 编译 Wine WOW64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v2

    - name: 缓存依赖项
      uses: actions/cache@v2
      with:
        path: |
          /usr/include
          /usr/lib
          /var/lib/apt/lists
          /var/cache/apt/archives
        key: ${{ runner.os }}-wine-dependencies-${{ hashFiles('**/wine-9.13.tar.xz') }}
        restore-keys: |
          ${{ runner.os }}-wine-dependencies-

    - name: 安装依赖项
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y gcc-multilib g++-multilib libc6-dev-i386
        sudo apt install -y libx11-dev:i386 libfreetype6-dev:i386 libxext-dev:i386 libxrender-dev:i386 libxi-dev:i386 libxt-dev:i386 libxxf86vm-dev:i386 libxrandr-dev:i386 libxfixes-dev:i386 libxml2-dev:i386 libasound2-dev:i386 libjpeg-dev:i386 libpng-dev:i386 libtiff-dev:i386 liblcms2-dev:i386 libgnutls28-dev:i386 libavcodec-dev:i386 libxcursor-dev:i386 libxkbfile-dev:i386 libxmu-dev:i386 libxpm-dev:i386 libxslt1-dev:i386 libosmesa6-dev:i386 libfontconfig1-dev:i386 libnss3-dev:i386 libnspr4-dev:i386 libgphoto2-dev:i386 libgstreamer1.0-dev:i386 libgstreamer-plugins-base1.0-dev:i386 libudev-dev:i386 libsane-dev:i386 libsdl2-dev:i386 libxtst-dev:i386 libpulse-dev:i386 libmpg123-dev:i386 libopenal-dev:i386 libncurses5:i386 libv4l-dev:i386 libxshmfence-dev:i386 libxxf86dga-dev:i386 libkrb5-dev:i386
    - name: 处理未满足的依赖关系
      run: |
        sudo apt-get -f install -y || true

    - name: 下载 Wine 9.13 源代码
      run: |
        wget https://dl.winehq.org/wine/source/9.x/wine-9.13.tar.xz
        tar -xvf wine-9.13.tar.xz

    - name: 编译 64 位 Wine
      run: |
        cd wine-9.13
        mkdir wine64
        cd wine64
        ../configure --prefix=/opt/wine64 --enable-win64
        make -j$(nproc)

    - name: 编译 32 位 Wine
      run: |
        cd wine-9.13
        mkdir wine32
        cd wine32
        ../configure --prefix=/opt/wine32 --with-wine64=../wine64
        make -j$(nproc)

    - name: 合并 32 位和 64 位 Wine
      run: |
        cd wine-9.13/wine32
        ../configure --prefix=/opt/wine --with-wine64=../wine64
        make -j$(nproc)

    - name: 打包 Wine 二进制文件
      run: |
        tar -czvf wine-wow64-9.13.tar.gz -C /opt wine

    - name: 上传构建工件
      uses: actions/upload-artifact@v2
      with:
        name: wine-wow64-9.13
        path: wine-wow64-9.13.tar.gz
