name: Build Wine WOW64 for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. 设置构建环境
    - name: Set up build environment
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-arm-linux-gnueabi g++-arm-linux-gnueabi gcc-multilib g++-multilib flex bison gettext libglib2.0-dev libfreetype6-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libjpeg-dev libpng-dev libosmesa6-dev libx11-dev libxml2-dev libxext-dev libxrender-dev libxslt1-dev

    # 3. 下载并解压Wine源代码
    - name: Download Wine source code
      run: |
        wget https://dl.winehq.org/wine/source/9.x/wine-9.13.tar.xz
        tar -xvf wine-9.13.tar.xz
        cd wine-9.13

    # 4. 构建64位版本的Wine
    - name: Build Wine 64-bit (ARM)
      run: |
        mkdir wine64-build
        cd wine64-build
        ../wine-9.13/configure --host=aarch64-linux-gnu --prefix=/opt/wine64 --enable-win64
        make -j$(nproc)
        make install
        cd ..

    # 5. 导出64位编译结果
    - name: Export 64-bit Wine build
      run: |
        tar -cvzf wine64-arm.tar.gz -C /opt/wine64 .
# 8. 打包WOW64版本的Wine
    - name: Package Wine WOW64
      run: |
        tar -cvzf wine-wow64-arm.tar.gz wine-wow64/

    # 9. 上传64位编译结果
    - name: Upload 64-bit Wine artifact
      uses: actions/upload-artifact@v2
      with:
        name: wine64-arm
        path: wine64-arm.tar.gz
    # 6. 构建32位版本的Wine
    - name: Build Wine 32-bit (ARM)
      run: |
        mkdir wine32-build
        cd wine32-build
        PKG_CONFIG_PATH=/opt/wine64/lib/pkgconfig ../wine-9.13/configure --host=arm-linux-gnueabihf --prefix=/opt/wine32 --with-wine64=../wine64-build
        make -j$(nproc)
        make install
        cd ..

    # 7. 合并32位和64位版本
    - name: Merge 32-bit and 64-bit Wine
      run: |
        mkdir -p wine-wow64
        cp -r /opt/wine64/* wine-wow64/
        cp -r /opt/wine32/* wine-wow64/


    # 10. 上传WOW64版本的Wine
    - name: Upload WOW64 artifact
      uses: actions/upload-artifact@v2
      with:
        name: wine-wow64-arm
        path: wine-wow64-arm.tar.gz
