name: Build Wine 9.13 Wow64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 更新和安装依赖
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y build-essential gcc-multilib g++-multilib libglib2.0-dev libc6-dev libc6-dev-i386 libfreetype6-dev libx11-dev libxext-dev libxrender-dev libxi-dev libxt-dev lib32z1-dev lib32ncurses5-dev libxcomposite-dev libxinerama-dev libxxf86vm-dev libxrandr-dev libxfixes-dev libxml2-dev libasound2-dev libgsm1-dev libjpeg-dev libpng-dev libtiff-dev libxinerama-dev libxrandr-dev liblcms2-dev libgnutls28-dev libavcodec-dev libxcomposite-dev libxcursor-dev libxkbfile-dev libxmu-dev libxpm-dev libxslt1-dev libosmesa6-dev gettext bison flex wget

    - name: 下载Wine源代码
      run: |
        wget https://dl.winehq.org/wine/source/9.x/wine-9.13.tar.xz
        tar -xf wine-9.13.tar.xz
        cd wine-9.13

    - name: 配置和编译64位
      run: |
        mkdir build64
        cd build64
        ../configure --enable-win64
        make

    - name: 配置和编译32位
      run: |
        cd ..
        mkdir build32
        cd build32
        PKG_CONFIG_PATH=/usr/lib/pkgconfig ../configure --with-wine64=../build64
        make

    - name: 打包
      run: |
        cd ../build64
        
        cd ../build32

        cd ..
        tar -czvf wine-9.13-wow64.tar.gz -C build64/wine64 .
        tar -czvf wine-9.13-wow64.tar.gz -C build32/wine32 .

    - name: 保存编译结果
      uses: actions/upload-artifact@v3
      with:
        name: wine-9.13-wow64
        path: wine-9.13-wow64.tar.gz
